### PR TITLE
extra options 2.0.0

### PR DESCRIPTION
**Pull request by tildejustin**
keeps the two sliders for distortion and fov, and a toggle for if bow is affected. options are stored in config/extra-options.txt in a format very similar to options.txt. there is an unlisted option called affectWater for people who need that. options are stored in the chat screen pre-1.14, which works fine. see #58.

### CODE REVIEW

**Comment by tildejustin** [comment]
source: https://github.com/tildejustin/extra-options

**Review by Knawk — APPROVED** [review]
Reviewed the source for each build, LGTM.

**Review by Knawk — DISMISSED** [review]
Latest source changes LGTM.

**Review by Knawk — APPROVED** [review]
LGTM

**Pull request merged**
