### PR TITLE
1.12.0 ports

### PR DESCRIPTION
**Pull request by tildejustin**
sources:
atum: https://github.com/tildejustin/atum/tree/1.12.0
forceport: https://github.com/tildejustin/forceport/tree/1.12
motiono: https://github.com/tildejustin/legacy-motioNO/tree/1.12
dfps: https://github.com/tildejustin/dynamic-fps/tree/1.12
set-spawn: https://github.com/tildejustin/mcsr-set-spawn/tree/1.12.0
standardsettings: https://github.com/tildejustin/StandardSettings/tree/1.12
state-output: https://github.com/tildejustin/state-output/commit/c90415a8853a76583b34f32a6d2c213a2ed5a5cc
tabfocus: https://github.com/tildejustin/tabfocus/tree/1.12.0
legacyplanarfog: https://github.com/tildejustin/legacyplanarfog

These mods target legacy fabric's in-development version 2 intermediaries, which have support for all subversions after 1.8.9 unlike the current production intermediaries. 1.12(.0) is the best version for the up-and-coming internal random seed category, and having mods helps a lot with play-ability, so I've been porting mods to the version. Since the mappings are in the middle of development, most names are unmapped, which makes working with this version quite a challenge. To port larger mods accurately, I created a set of translation mappings (https://github.com/tildejustin/legacy-fabric-intermediary-updater/blob/main/1.12.2%2Bbuild.202206171821-1.12.2%2Bbuild.536-translation.tiny), which map v1 intermediary -> v2 named so that loom's migrateMappings & mercury can do all the hard work, and I only had to do mixin strings. This is an interesting case for legalization, I doubt all the original repo owners want these ports on their repos, but they will be important once the internal category is created.

### CODE REVIEW

**Comment by tildejustin** [comment]
reminder to remove srigt

**Comment by DuncanRuns** [comment]
I am reminding you to remove srigt

**Review by DuncanRuns — APPROVED** [review]
Approval because they won't be breaking 1.12 with intermediary regen apparently
and also I did go through and check sources and such as usual

**Comment by tildejustin** [comment]
srigt source: https://github.com/RedLime/SpeedRunIGT/tree/aa19c40f655e2d7f716186b4a36ee47e1bb9490b

**Review by DuncanRuns — APPROVED** [review]

**Pull request merged**
