### PR TITLE
Allow more versions for forceport

### PR DESCRIPTION
**Pull request by DuncanRuns**
Just changes the allowed versions for forceport to what forceport actually can support.

This will let minimal changes to macros support a coop mode in modern versions.

### CODE REVIEW

**Review by tildejustin — CHANGES_REQUESTED** [review]
can you make the folder `1.14+` instead of tying it to a certain max version? it is defined in the readme as a possible option.

**Comment by DuncanRuns** [comment]
so true

**Comment by DuncanRuns** [comment]
Also made https://github.com/Minecraft-Java-Edition-Speedrunning/archive-forceport just to teach myself real quick

**Review by tildejustin — APPROVED** [review]
applaudable work you've done here

**Pull request merged**
