### PR TITLE
fast reset 1.4.2

### PR DESCRIPTION
**Pull request by tildejustin**
sources: https://github.com/Minecraft-Java-Edition-Speedrunning/FastReset + prs
I didn't bother with 1.15 because it already has the `deleteSessionLock` commented out, I could add the CME suppression but it didn't seem worth it...

### CODE REVIEW

**Review by DuncanRuns — DISMISSED** [review]

**Comment by tildejustin** [comment]
added 1.18+ ports

**Review by DuncanRuns — COMMENTED** [review]
PR contains a change to `conditional-mods.json` for some reason

**Comment by tildejustin** [comment]
oh yeah I was probably on that branch when I made the commit, then made the other change

**Review by DuncanRuns — APPROVED** [review]

**Comment by tildejustin** [comment]
suppress ise and cme

**Pull request merged**
