### PR TITLE
motiono 1.3.1-1.16.1

### PR DESCRIPTION
**Pull request by tildejustin**
source: [tildejustin/legacy-motioNO](https://github.com/tildejustin/legacy-motioNO)
backport of motiono
I put this in the motiono folder even though it has a different mod id (same with forceport), I think it makes more sense like this but if we want to be strict on it I can change it.

### CODE REVIEW

**Comment by DuncanRuns** [comment]
Mixes into a client player method called `getSpeed()`, will this not affect the literal speed of the player? or is it just bad method naming

**Comment by DuncanRuns** [comment]
> Mixes into a client player method called `getSpeed()`, will this not affect the literal speed of the player? or is it just bad method naming

image

**Review by DuncanRuns — DISMISSED** [review]

**Comment by tildejustin** [comment]
new source location: https://github.com/Minecraft-Java-Edition-Speedrunning/motiono

**Review by DuncanRuns — APPROVED** [review]

**Comment by tildejustin** [comment]
for 1.14+: remove config and config screen

**Pull request merged**
