### PR TITLE
Accessibility update

### PR DESCRIPTION
**Pull request by DuncanRuns**
Renamed branch so old PR got killed lol
TODO:
- [x] Remove MotioNO from conditional-mods.json
- [x] Remove MotioNO entirely (final decision?)
- [x] Remove extra-options from conditional-mods.json
  - [x] Remove Accessibility Mods section from readme.md and conditional-mods.json (and src later)
- [x] Update extra-options (final decision?) (separate PR that comes before this?)

### CODE REVIEW

**Comment by DuncanRuns** [comment]
We will want extra-options update to be merged before this (or included in this PR), so that there is no amount of time where old extra-options is legal for everyone

**Comment by DuncanRuns** [comment]
(I drifted away from the convo cause of lack of interest and knawk be chattin bout it a lot)

**Comment by DuncanRuns** [comment]
Remember to merge #59 before this one

**Review by tildejustin — APPROVED** [review]
lgtm lol

**Pull request merged**
