### PR TITLE
retino

### PR DESCRIPTION
**Pull request by tildejustin**
source: https://github.com/juliand665/retiNO/blob/master/src/main/java/retino/mixin/WindowHintsMixin.java
also took the opportunity to alphabetize the ssg only mod list

### CODE REVIEW

**Comment by tildejustin** [comment]
on staging

**Review by Knawk — APPROVED** [review]
LGTM

**Comment by DuncanRuns** [comment]
why does the conditional-mods.json change swap the order of ssg mods? 🤔

**Comment by Knawk** [comment]
maybe for alphabetical order? 🤷

**Pull request merged**
