### PR TITLE
Mod Updates

### PR DESCRIPTION
**Pull request by KingContaria**
I've tested these builds in prod, did a couple resets, tested out the features and fixes, no issues on my machine.

AntiResourceReload 5.1.0
- cache UserCache (see https://github.com/Minecraft-Java-Edition-Speedrunning/antiresourcereload/pull/12)

Atum 2.1
- fix not being able to bind the reset key to a mouse button
- set default difficulty back to easy, reset this setting to default

FastReset 2.1
- add "Always save after..." option

StandardSettings 2.1
- don't show raw mouse input standardsettings on systems where its not supported
- add main hand standardsetting
- add "Toggle All" button

SeedQueue 1.1
- remember preview positions on wall
- fix issues with standardsettings cache implementation with wall screen
- dont play music on wall screen
- log some hardware information for easier debugging
- remove OpenGL error message suppression as the underlying issue was fixed in 1.0.2
- misc fixes

SpeedrunAPI 1.0.1
 - fix list height not being adjusted correctly when resizing with search field active
 - enable keyboard repeat events on config screens

### CODE REVIEW

**Comment by KingContaria** [comment]
I must've messed up something along the way, SeedQueue 1.0.2 is of course not part of this PR

**Comment by tildejustin** [comment]
you should rebase on main, otherwise the merge won't delete the 1.0.2 jar

**Comment by tildejustin** [comment]
well, it might since you also have a version of the 1.0.2 commit but i don't want to risk it

**Comment by KingContaria** [comment]
Okay i definitely didn't do it right but just merge with squash and it should be fine

**Review by tildejustin — APPROVED** [review]

**Pull request merged**
